import { mkdir, writeFile } from 'node:fs/promises';
import path from 'node:path';
import { canonicalStringify, sha256 } from '../ir/index.mjs';
import { verifyFrozenAsset } from '../workflow/index.mjs';

export const compiler = {
  id: 'playwright',
  version: '2.0.0',
  supportedIrVersions: ['1'],
};

const DEFAULT_OPTIONS = Object.freeze({
  testModule: '@playwright/test',
  driverModule: './gui-driver.mjs',
  fileExtension: '.spec.mjs',
  fixtureNames: ['page'],
});

const JAVASCRIPT_IDENTIFIER = /^[A-Za-z_$][A-Za-z0-9_$]*$/;
const SUPPORTED_EXTENSIONS = new Set(['.spec.js', '.spec.mjs', '.spec.ts']);

function normalizeOptions(options = {}) {
  const normalized = {
    testModule: options.testModule ?? DEFAULT_OPTIONS.testModule,
    driverModule: options.driverModule ?? DEFAULT_OPTIONS.driverModule,
    fileExtension: options.fileExtension ?? DEFAULT_OPTIONS.fileExtension,
    fixtureNames: options.fixtureNames ?? DEFAULT_OPTIONS.fixtureNames,
  };
  for (const field of ['testModule', 'driverModule']) {
    if (typeof normalized[field] !== 'string' || normalized[field].trim() === '' || /[\r\n]/.test(normalized[field])) {
      throw new Error(`${field} must be a non-empty module specifier`);
    }
  }
  if (!SUPPORTED_EXTENSIONS.has(normalized.fileExtension)) {
    throw new Error(`Unsupported Playwright spec extension: ${normalized.fileExtension}`);
  }
  if (!Array.isArray(normalized.fixtureNames) || normalized.fixtureNames.length === 0) {
    throw new Error('fixtureNames must contain at least one fixture name');
  }
  const fixtureNames = [...new Set(normalized.fixtureNames)];
  for (const fixtureName of fixtureNames) {
    if (!JAVASCRIPT_IDENTIFIER.test(fixtureName)) {
      throw new Error(`Invalid Playwright fixture name: ${JSON.stringify(fixtureName)}`);
    }
  }
  return { ...normalized, fixtureNames };
}

function generatedSource(asset, options) {
  const fixtureList = options.fixtureNames.join(', ');
  const casesJson = JSON.stringify(asset.cases, null, 2);
  return `// Generated by GUI TestForge. Do not edit.\n` +
    `// Frozen asset: ${asset.assetHash}\n` +
    `import { test, expect } from ${JSON.stringify(options.testModule)};\n` +
    `import { createDriver } from ${JSON.stringify(options.driverModule)};\n\n` +
    `export const frozenAssetHash = ${JSON.stringify(asset.assetHash)};\n` +
    `export const testCases = ${casesJson};\n\n` +
    `for (const testCase of testCases) {\n` +
    `  test(\`\${testCase.id} · \${testCase.title}\`, async ({ ${fixtureList} }) => {\n` +
    `    const driver = await createDriver({ ${fixtureList}, caseId: testCase.id, fixture: testCase.fixture });\n` +
    `    const missingMethods = ['act', 'observe', 'close'].filter((name) => typeof driver?.[name] !== 'function');\n` +
    `    if (missingMethods.length > 0) throw new Error(\`DRIVER_NOT_IMPLEMENTED: missing methods \${missingMethods.join(', ')}\`);\n` +
    `    try {\n` +
    `      for (let stepIndex = 0; stepIndex < testCase.steps.length; stepIndex += 1) {\n` +
    `        const step = testCase.steps[stepIndex];\n` +
    `        await test.step(\`\${stepIndex + 1}. \${step.action.name}\`, async () => {\n` +
    `          await driver.act(step.action);\n` +
    `          for (const assertion of step.assertions) {\n` +
    `            const query = { target: assertion.target, args: assertion.args ?? {} };\n` +
    `            const actual = await driver.observe(query);\n` +
    `            expect(actual, \`\${testCase.id}: \${assertion.target}\`).toEqual(assertion.equals);\n` +
    `          }\n` +
    `        });\n` +
    `      }\n` +
    `      const businessOutcome = await driver.observe({ target: 'businessOutcome', args: {} });\n` +
    `      expect(businessOutcome, \`\${testCase.id}: businessOutcome\`).toEqual(testCase.expectedBusinessOutcome);\n` +
    `    } finally {\n` +
    `      await driver.close();\n` +
    `    }\n` +
    `  });\n` +
    `}\n`;
}

function createDriverContract(asset) {
  return {
    format: 'gui-testforge-driver-contract',
    version: 1,
    frozenAssetHash: asset.assetHash,
    factoryExport: 'createDriver',
    factoryInput: ['fixtures', 'caseId', 'fixture'],
    methods: ['act', 'observe', 'close'],
    semantics: asset.semanticContract,
  };
}

export async function compileFrozenAsset(asset, outputDirectory, rawOptions = {}) {
  if (!verifyFrozenAsset(asset)) throw new Error('Frozen asset hash verification failed');
  if (!compiler.supportedIrVersions.includes(asset.irVersion)) {
    throw new Error(`Unsupported Test IR version: ${asset.irVersion}`);
  }
  const options = normalizeOptions(rawOptions);
  const source = generatedSource(asset, options).replace(/\r\n/g, '\n');
  const entryFile = `testforge.generated${options.fileExtension}`;
  const driverContractFile = 'driver-contract.json';
  const casesFile = 'test-cases.json';
  const driverContractSource = `${canonicalStringify(createDriverContract(asset))}\n`;
  const casesSource = `${canonicalStringify(asset.cases)}\n`;
  const manifest = {
    format: 'gui-testforge-compiled-bundle',
    version: 2,
    framework: 'playwright-test',
    compilerId: compiler.id,
    compilerVersion: compiler.version,
    irVersion: asset.irVersion,
    frozenAssetHash: asset.assetHash,
    semanticContractHash: sha256(asset.semanticContract),
    compilerConfigHash: sha256(options),
    entryFile,
    driverContractFile,
    casesFile,
    files: {
      [entryFile]: sha256(source),
      [driverContractFile]: sha256(driverContractSource),
      [casesFile]: sha256(casesSource),
    },
    cases: asset.cases.map((testCase) => ({ id: testCase.id, requirementRefs: testCase.requirementRefs })),
    discoveryCommand: 'playwright test --list',
    executionCommand: 'playwright test',
    peerDependencies: { '@playwright/test': '>=1.45.0 <2' },
  };
  await mkdir(outputDirectory, { recursive: true });
  await writeFile(path.join(outputDirectory, entryFile), source, 'utf8');
  await writeFile(path.join(outputDirectory, driverContractFile), driverContractSource, 'utf8');
  await writeFile(path.join(outputDirectory, casesFile), casesSource, 'utf8');
  await writeFile(path.join(outputDirectory, 'manifest.json'), `${canonicalStringify(manifest)}\n`, 'utf8');
  return manifest;
}
